fix typo
OpusVL/odoo-account-extras pull request #5
Opened 2019-06-06 09:33 UTC by luc-demeyer

fix typo : gorups -> groups

2019-06-07 11:02 UTC, Nick-OpusVL requested changes

2019-06-07 11:02 UTC, Nick-OpusVL commented on account_mtd/security/groups.xml
> +        <record id="mtd_groups_category" model="ir.module.category">
Could you rename its usages too?

2019-06-07 11:02 UTC, Nick-OpusVL commented on account_mtd_vat/security/groups.xml
> +        <record id="mtd_vat_groups_category" model="ir.module.category">
Could you rename its usages too?

2019-06-07 14:19 UTC, luc-demeyer commented
@Nick-OpusVL 
refs now also aligned.

2019-06-27 11:21 UTC, Nick-OpusVL commented
@ManishS-OpusVL I'd like to get this contribution rebased, tested and ported across the odoo versions before we give this to the wide world.  Less risk (though risk is low anyway) to apply and test now than when lots of users.

2019-07-08 11:25 UTC, Nick-OpusVL commented
Merged manually after rebase and test.  Thanks @luc-demeyer

2019-07-08 11:25 UTC, closed without merging